name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkout:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./server/package-lock.json"

  install-client-dependecies-and-build:
    runs-on: self-hosted
    needs: checkout

    steps:
      - name: Install dependecies
        run: |
          cd /home/ubuntu/actions-runner/_work/test-deploy/test-deploy/client
          npm install
      - name: Build
        run: |
          cd /home/ubuntu/actions-runner/_work/test-deploy/test-deploy/client
          npm run build

  install-server-dependecies:
    runs-on: self-hosted
    needs: install-client-dependecies-and-build

    steps:
      - name: Install dependecies
        run: |
          cd /home/ubuntu/actions-runner/_work/test-deploy/test-deploy/server
          npm install
      - run: sudo systemctl restart nginx
