name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependecies
        run: |
          cd /home/ubuntu/actions-runner/_work/test-deploy/test-deploy/client
          npm install
          cd /home/ubuntu/actions-runner/_work/test-deploy/test-deploy/server
          npm install
      - name: Build
        run: |
          cd /home/ubuntu/actions-runner/_work/test-deploy/test-deploy/client
          npm run build --if-present
      - run: sudo systemctl restart nginx
